gem 'rails', '4.0.2'
gem 'sass-rails'
# gem 'twitter-bootstrap-rails'
gem 'bootstrap-sass'
gem 'therubyracer'

group :development, :production do
  gem 'mailcatcher'
  gem 'net-ssh', '2.9.2'
end

gem 'pg'
gem 'puma'
gem 'less-rails'
gem 'paperclip'
gem 'pry'
gem 'friendly_id'
gem 'email_validator'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'redcarpet'
gem 'devise'
gem 'newrelic_rpm'
gem 'markdown-rails'
gem 'pygments.rb'
gem 'nokogiri'
gem 'quiet_assets', :group => :development
gem 'colorize'
